# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Марка')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Модель')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Marks', verbose_name='Марка')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=32, verbose_name='Двигатель')),
                ('body', models.CharField(max_length=32, verbose_name='Кузов')),
                ('doors', models.PositiveIntegerField(verbose_name='Дверей')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность')),
                ('drive', models.CharField(max_length=32, verbose_name='Привод')),
                ('fuel', models.CharField(max_length=32, verbose_name='Топливо')),
                ('years', models.CharField(max_length=32, verbose_name='Год')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Marks', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Models', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Серия')),
                ('image', models.ImageField(upload_to='series', verbose_name='Фото')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Marks', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Models', verbose_name='Модель')),
            ],
        ),
        migrations.AddField(
            model_name='modification',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Series', verbose_name='Серия'),
        ),
    ]
